#!/bin/bash
set -e
source_name=$1
target_name=$2
if [ -z "$source_name" ] || [ -z "$target_name" ]; then
    echo "Usage: $0 <source_name> <target_name>"
    exit 1
fi
huggingface-cli upload-large-folder EleutherAI/$target_name checkpoints/$source_name --repo-type model
